apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: cronjobs
spec:
  schedule: "*/1 * * * *"
  data: "{\"message\": \"Hello world!\"}"
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: testchannel